[package]
name = "linked_list_the_sequel"
version = "0.1.0"
authors = ["RCurtis <rjcurtis22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name="linked_list_the_sequel"
path="src/lib.rs"

[dependencies]
